services:
  - type: web
    name: marlink-api
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
